## Introduction
[Alpaca Trading API](https://github.com/alpacahq/alpaca-trade-api-python) is an API using which we can retrieve stock data in realtime. It provides various APIs and even streaming services. Please read about it in their [docs](https://alpaca.markets/docs/trading/). What is most exciting about this API and the librariy is that it returns the data as a Pandas Dataframe or even simple Dict object. And here we will focus on how to do real time stock market data retrieval.

## Getting API Keys
* To access API, we need to have an account. So lets signup in https://app.alpaca.markets/signup. Then fill up the form and go to the home page.
* In order to make first ever API request, we need to have API keys and secret. So go to [papertrading and signup for keys](https://app.alpaca.markets/paper/dashboard/overview). **It requires real identity card and live camera at some point**.
* Save your API Keys and Secret somewhere safe.

### Making First Request
* Install the library first using `pip3 install alpaca-trade-api`. Or your own package manager in Python.

In [ ]:
!pip3 install alpaca-trade-api

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting alpaca-trade-api
  Downloading alpaca_trade_api-2.2.0-py3-none-any.whl (33 kB)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.7/dist-packages (from alpaca-trade-api) (1.21.6)
Requirement already satisfied: requests<3,>2 in /usr/local/lib/python3.7/dist-packages (from alpaca-trade-api) (2.23.0)
Collecting websocket-client<2,>=0.56.0
  Downloading websocket_client-1.3.2-py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 3.0 MB/s
Collecting PyYAML==6.0
  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
     |████████████████████████████████| 596 kB 15.9 MB/s
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.7/dist-packages (from alpaca-trade-api) (1.3.5)
Collecting aiohttp==3.8.1
  Downloading aiohttp-3.8.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 30.0 MB/s
Collecting websockets<11,>=9.0
  Downloading websockets-10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (112 kB)
     |████████████████████████████████| 112 kB 50.2 MB/s
Requirement already satisfied: msgpack==1.0.3 in /usr/local/lib/python3.7/dist-packages (from alpaca-trade-api) (1.0.3)
Collecting deprecation==2.1.0
  Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: urllib3<2,>1.24 in /usr/local/lib/python3.7/dist-packages (from alpaca-trade-api) (1.24.3)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting asynctest==0.13.0
  Downloading asynctest-0.13.0-py3-none-any.whl (26 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.7.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (271 kB)
     |████████████████████████████████| 271 kB 77.0 MB/s
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
     |████████████████████████████████| 144 kB 13.8 MB/s
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from aiohttp==3.8.1->alpaca-trade-api) (4.2.0)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (94 kB)
     |████████████████████████████████| 94 kB 4.3 MB/s
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp==3.8.1->alpaca-trade-api) (21.4.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp==3.8.1->alpaca-trade-api) (2.0.12)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from deprecation==2.1.0->alpaca-trade-api) (21.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.18.1->alpaca-trade-api) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3,>2->alpaca-trade-api) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3,>2->alpaca-trade-api) (2022.5.18.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3,>2->alpaca-trade-api) (3.0.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->deprecation==2.1.0->alpaca-trade-api) (3.0.9)
Installing collected packages: multidict, frozenlist, yarl, asynctest, async-timeout, aiosignal, websockets, websocket-client, PyYAML, deprecation, aiohttp, alpaca-trade-api
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
Successfully installed PyYAML-6.0 aiohttp-3.8.1 aiosignal-1.2.0 alpaca-trade-api-2.2.0 async-timeout-4.0.2 asynctest-0.13.0 deprecation-2.1.0 frozenlist-1.3.0 multidict-6.0.2 websocket-client-1.3.2 websockets-10.3 yarl-1.7.2

In [ ]:
import pandas as pd

key="susssh"
secret="sshhhhh"

Please insert your generated keys in above variable.

In [ ]:
import alpaca_trade_api as tradeapi

# to which url we will send request
base_url="https://paper-api.alpaca.markets"

# instantiate REST API
api = tradeapi.REST(key, secret, base_url, api_version='v2')

# obtain account information
account = api.get_account()
print(account)

Account({   'account_blocked': False,
    'account_number': 'PA3BQI9QBTE3',
    'accrued_fees': '0',
    'buying_power': '200000',
    'cash': '100000',
    'created_at': '2022-04-30T14:29:12.722985Z',
    'crypto_status': 'ACTIVE',
    'currency': 'USD',
    'daytrade_count': 0,
    'daytrading_buying_power': '0',
    'equity': '100000',
    'id': 'ddeb8bc4-87d3-4ade-8b4a-8a40c7207fed',
    'initial_margin': '0',
    'last_equity': '100000',
    'last_maintenance_margin': '0',
    'long_market_value': '0',
    'maintenance_margin': '0',
    'multiplier': '2',
    'non_marginable_buying_power': '100000',
    'pattern_day_trader': False,
    'pending_transfer_in': '0',
    'portfolio_value': '100000',
    'regt_buying_power': '200000',
    'short_market_value': '0',
    'shorting_enabled': True,
    'sma': '100000',
    'status': 'ACTIVE',
    'trade_suspended_by_user': False,
    'trading_blocked': False,
    'transfers_blocked': False})

It shows that the fresh new account that I just created.

## Getting List of Symbols
We can get the list of assets like below.

In [ ]:

active_assets=api.list_assets(status='active')
for asset in active_assets:
  print(asset)
  break

Asset({   'class': 'us_equity',
    'easy_to_borrow': False,
    'exchange': 'OTC',
    'fractionable': False,
    'id': '82c93418-a2d1-43f0-beb8-c204714fff15',
    'marginable': False,
    'name': 'Weidai Ltd American Depositary Receipts - Sponsored (Cayman '
            'Islands)',
    'shortable': False,
    'status': 'active',
    'symbol': 'WEIDY',
    'tradable': False})

In [ ]:
clock=api.get_clock()
clock

Clock({   'is_open': True,
    'next_close': '2022-06-09T16:00:00-04:00',
    'next_open': '2022-06-10T09:30:00-04:00',
    'timestamp': '2022-06-09T13:34:52.486647597-04:00'})

In [ ]:
clock.timestamp, clock.timestamp.to_pydatetime()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: UserWarning: Discarding nonzero nanoseconds in conversion
  exec(code_obj, self.user_global_ns, self.user_ns)

(Timestamp('2022-06-09 13:34:52.486647597-0400', tz='pytz.FixedOffset(-240)'),
 datetime.datetime(2022, 6, 9, 13, 34, 52, 486647, tzinfo=pytz.FixedOffset(-240)))

## Rest APIs
Alpaca provides various REST APIs that handles the most common requests like getting trade, quote, floorsheet.

### Get Floorsheet Data

Now is the time to make first request to get data. So lets define a list of stock symbols that we will be focusing on. We will focus on Tesla and Apple stocks. And we want to see floorsheet value of each minute.

In terms of Alpaca, its bars.

#### All At one time
We can get all data at one time or iterate over it. Getting all data is little bit slow and might require extra memory.

In [ ]:
symbols = ["AAPL"]
resp = api.get_bars(symbols,timeframe='1Min', start="2022-06-09",limit=None)
df = resp.df.reset_index()
df

,timestamp,open,high,low,close,volume,trade_count,vwap,symbol
0,2022-06-09 08:00:00+00:00,147.80,147.800,147.6700,147.8000,1306,60,147.722228,AAPL
1,2022-06-09 08:03:00+00:00,147.68,147.680,147.6800,147.6800,1128,45,147.659973,AAPL
2,2022-06-09 08:04:00+00:00,147.68,147.680,147.6800,147.6800,150,7,147.678000,AAPL
3,2022-06-09 08:05:00+00:00,147.65,147.650,147.6000,147.6000,741,21,147.625209,AAPL
4,2022-06-09 08:07:00+00:00,147.59,147.590,147.5900,147.5900,375,12,147.589493,AAPL
...,...,...,...,...,...,...,...,...,...
563,2022-06-09 19:07:00+00:00,144.12,144.170,144.0300,144.0900,185402,1596,144.093568,AAPL
564,2022-06-09 19:08:00+00:00,144.10,144.125,143.8850,144.1190,456874,4947,143.996047,AAPL
565,2022-06-09 19:09:00+00:00,144.12,144.140,144.0450,144.0850,169569,1351,144.089903,AAPL
566,2022-06-09 19:10:00+00:00,144.09,144.160,144.0105,144.0646,165695,1465,144.089207,AAPL
567,2022-06-09 19:11:00+00:00,144.07,144.150,144.0300,144.1300,166490,1356,144.093201,AAPL

In [ ]:
df.groupby(pd.Grouper(key="timestamp", freq="5min")).agg(start=("timestamp", "first"), end=("timestamp", "last")).reset_index()

,timestamp,start,end
0,2022-06-09 08:00:00+00:00,2022-06-09 08:00:00+00:00,2022-06-09 08:04:00+00:00
1,2022-06-09 08:05:00+00:00,2022-06-09 08:05:00+00:00,2022-06-09 08:09:00+00:00
2,2022-06-09 08:10:00+00:00,2022-06-09 08:12:00+00:00,2022-06-09 08:13:00+00:00
3,2022-06-09 08:15:00+00:00,2022-06-09 08:15:00+00:00,2022-06-09 08:19:00+00:00
4,2022-06-09 08:20:00+00:00,2022-06-09 08:21:00+00:00,2022-06-09 08:21:00+00:00
...,...,...,...
130,2022-06-09 18:50:00+00:00,2022-06-09 18:50:00+00:00,2022-06-09 18:54:00+00:00
131,2022-06-09 18:55:00+00:00,2022-06-09 18:55:00+00:00,2022-06-09 18:59:00+00:00
132,2022-06-09 19:00:00+00:00,2022-06-09 19:00:00+00:00,2022-06-09 19:04:00+00:00
133,2022-06-09 19:05:00+00:00,2022-06-09 19:05:00+00:00,2022-06-09 19:09:00+00:00
134,2022-06-09 19:10:00+00:00,2022-06-09 19:10:00+00:00,2022-06-09 19:11:00+00:00

Today is Friday and hence there will not be any data at the moment. Thus, we will need to change start date to yesterday.

In [ ]:
symbols = ["TSLA", "AAPL"]
resp = api.get_bars(symbols,timeframe='1Min', start="2022-04-29",limit=None)
resp.df.reset_index()

,timestamp,open,high,low,close,volume,trade_count,vwap,symbol
0,2022-04-29 08:00:00+00:00,161.0000,161.50,160.3600,160.3600,6107,116,160.736835,AAPL
1,2022-04-29 08:01:00+00:00,160.7400,160.84,160.7000,160.7700,3929,87,160.773235,AAPL
2,2022-04-29 08:02:00+00:00,160.8400,160.84,160.7700,160.7700,2929,69,160.803947,AAPL
3,2022-04-29 08:03:00+00:00,160.7500,160.77,160.7000,160.7700,3335,71,160.734747,AAPL
4,2022-04-29 08:04:00+00:00,160.7800,160.98,160.7700,160.9800,1496,42,160.826170,AAPL
...,...,...,...,...,...,...,...,...,...
18625,2022-05-16 17:49:00+00:00,730.7500,730.75,729.0800,729.4750,64288,1428,729.774911,TSLA
18626,2022-05-16 17:50:00+00:00,729.6400,731.00,729.2994,729.9500,29620,913,730.252701,TSLA
18627,2022-05-16 17:51:00+00:00,730.0000,730.82,729.8950,730.5834,18395,634,730.217622,TSLA
18628,2022-05-16 17:52:00+00:00,730.4837,731.44,730.0800,731.0150,29788,776,730.818045,TSLA
18629,2022-05-16 17:53:00+00:00,731.0364,731.18,729.3550,729.3700,25177,837,730.394841,TSLA

Now looking over the dataframe above, we can see that there are 1731 rows with floorsheet value of each minute for each stock.

##### Custom Timeframe

We can even get floorsheet data of every 45, 10, 30 minute or even more customized using `TimeFrame` and `TimeFrameUnit` given by its package.

In [ ]:
from alpaca_trade_api.rest import TimeFrame, TimeFrameUnit

df = api.get_bars(symbols, TimeFrame(13, TimeFrameUnit.Minute), "2022-04-29").df.reset_index()
df

,timestamp,open,high,low,close,volume,trade_count,vwap,symbol
0,2022-04-29 07:57:00+00:00,161.0000,161.50,160.3600,160.6200,46766,847,160.805158,AAPL
1,2022-04-29 08:10:00+00:00,160.6300,160.78,160.5200,160.5600,53331,755,160.655755,AAPL
2,2022-04-29 08:23:00+00:00,160.5600,160.63,159.6300,160.0000,72334,1059,160.035541,AAPL
3,2022-04-29 08:36:00+00:00,159.9200,160.00,159.8500,160.0000,15276,349,159.939272,AAPL
4,2022-04-29 08:49:00+00:00,159.9600,160.00,159.7400,159.8000,14169,347,159.896077,AAPL
...,...,...,...,...,...,...,...,...,...
1722,2022-05-16 16:49:00+00:00,732.1017,734.07,727.3000,728.8421,645566,19633,729.962528,TSLA
1723,2022-05-16 17:02:00+00:00,728.8699,730.47,725.2600,726.2875,813752,21650,728.189101,TSLA
1724,2022-05-16 17:15:00+00:00,726.1200,728.89,719.0885,728.3000,1131352,37088,723.686519,TSLA
1725,2022-05-16 17:28:00+00:00,728.1450,735.47,727.9800,734.7200,877881,22947,731.381328,TSLA
1726,2022-05-16 17:41:00+00:00,734.9800,736.66,729.0800,729.3700,584402,14635,731.652756,TSLA

In above example, we are looking for floorsheet of every 13 minutes. We can even use Hour there.

#### Iterating Over
Instead of getting entire data, it might be a good idea to loop through if we have many rows. Thus we can get a iterable and iterate over it like below.

In [ ]:
fls = api.get_bars_iter(symbols, TimeFrame(10, TimeFrameUnit.Hour), "2022-04-29")
for fs in fls:
  print(fs)

Bar({   'S': 'AAPL',
    'c': 160.01,
    'h': 166.2,
    'l': 158.97,
    'n': 699101,
    'o': 161,
    't': '2022-04-29T08:00:00Z',
    'v': 75360694,
    'vw': 162.450706})
Bar({   'S': 'AAPL',
    'c': 157.93,
    'h': 160.39,
    'l': 157.25,
    'n': 323819,
    'o': 160,
    't': '2022-04-29T18:00:00Z',
    'v': 56041611,
    'vw': 158.373787})
Bar({   'S': 'AAPL',
    'c': 155.845,
    'h': 158.8,
    'l': 154.59,
    'n': 565048,
    'o': 158.6,
    't': '2022-05-02T06:00:00Z',
    'v': 53875946,
    'vw': 156.202149})
Bar({   'S': 'AAPL',
    'c': 157.91,
    'h': 158.3,
    'l': 153.27,
    'n': 579928,
    'o': 155.84,
    't': '2022-05-02T16:00:00Z',
    'v': 68669384,
    'vw': 155.894038})
Bar({   'S': 'AAPL',
    'c': 158.06,
    'h': 158.71,
    'l': 157.01,
    'n': 3903,
    'o': 158.1,
    't': '2022-05-03T02:00:00Z',
    'v': 176030,
    'vw': 157.877219})
Bar({   'S': 'AAPL',
    'c': 159.7,
    'h': 160.71,
    'l': 156.32,
    'n': 693885,
    'o': 158.13,
    't': '2022-05-03T12:00:00Z',
    'v': 88250242,
    'vw': 158.802582})
Bar({   'S': 'AAPL',
    'c': 159.68,
    'h': 159.94,
    'l': 159.45,
    'n': 1254,
    'o': 159.7,
    't': '2022-05-03T22:00:00Z',
    'v': 61383,
    'vw': 159.617482})
Bar({   'S': 'AAPL',
    'c': 162.6,
    'h': 162.92,
    'l': 159.22,
    'n': 432871,
    'o': 159.88,
    't': '2022-05-04T08:00:00Z',
    'v': 52644986,
    'vw': 160.6167})
Bar({   'S': 'AAPL',
    'c': 165.77,
    'h': 166.48,
    'l': 159.66,
    'n': 431333,
    'o': 162.58,
    't': '2022-05-04T18:00:00Z',
    'v': 55640662,
    'vw': 164.100594})
Bar({   'S': 'AAPL',
    'c': 161.64,
    'h': 165.33,
    'l': 161.24,
    'n': 129250,
    'o': 164.39,
    't': '2022-05-05T04:00:00Z',
    'v': 13119436,
    'vw': 162.953133})
Bar({   'S': 'AAPL',
    'c': 157.96,
    'h': 161.78,
    'l': 154.95,
    'n': 1025785,
    'o': 161.64,
    't': '2022-05-05T14:00:00Z',
    'v': 116673745,
    'vw': 157.59427})
Bar({   'S': 'AAPL',
    'c': 156.82,
    'h': 157.3,
    'l': 156.2,
    'n': 2787,
    'o': 157.29,
    't': '2022-05-06T00:00:00Z',
    'v': 91373,
    'vw': 156.676035})
Bar({   'S': 'AAPL',
    'c': 157.35,
    'h': 159.44,
    'l': 154.18,
    'n': 1002804,
    'o': 156.84,
    't': '2022-05-06T10:00:00Z',
    'v': 105449440,
    'vw': 157.339292})
Bar({   'S': 'AAPL',
    'c': 157.15,
    'h': 157.47,
    'l': 156.65,
    'n': 6241,
    'o': 157.47,
    't': '2022-05-06T20:00:00Z',
    'v': 9856702,
    'vw': 157.265374})
Bar({   'S': 'AAPL',
    'c': 152.55,
    'h': 155.83,
    'l': 151.56,
    'n': 777157,
    'o': 155.26,
    't': '2022-05-09T08:00:00Z',
    'v': 84639874,
    'vw': 153.524566})
Bar({   'S': 'AAPL',
    'c': 152.75,
    'h': 153.61,
    'l': 151.49,
    'n': 312023,
    'o': 152.5483,
    't': '2022-05-09T18:00:00Z',
    'v': 46314346,
    'vw': 152.323672})
Bar({   'S': 'AAPL',
    'c': 155.805,
    'h': 156.54,
    'l': 153.19,
    'n': 179876,
    'o': 153.52,
    't': '2022-05-10T04:00:00Z',
    'v': 20530135,
    'vw': 154.917637})
Bar({   'S': 'AAPL',
    'c': 154.5,
    'h': 156.74,
    'l': 152.93,
    'n': 797397,
    'o': 155.83,
    't': '2022-05-10T14:00:00Z',
    'v': 93761308,
    'vw': 154.83051})
Bar({   'S': 'AAPL',
    'c': 156.48,
    'h': 156.89,
    'l': 155.15,
    'n': 2136,
    'o': 155.28,
    't': '2022-05-11T00:00:00Z',
    'v': 138346,
    'vw': 155.987718})
Bar({   'S': 'AAPL',
    'c': 146.59,
    'h': 156.74,
    'l': 145.81,
    'n': 1265950,
    'o': 156.44,
    't': '2022-05-11T10:00:00Z',
    'v': 127423389,
    'vw': 149.754256})
Bar({   'S': 'AAPL',
    'c': 146.67,
    'h': 147.2,
    'l': 146,
    'n': 26802,
    'o': 146.6,
    't': '2022-05-11T20:00:00Z',
    'v': 14355445,
    'vw': 146.501852})
Bar({   'S': 'AAPL',
    'c': 141.25,
    'h': 146.59,
    'l': 140.0915,
    'n': 845000,
    'o': 146.59,
    't': '2022-05-12T06:00:00Z',
    'v': 86418477,
    'vw': 143.134756})
Bar({   'S': 'AAPL',
    'c': 143.9,
    'h': 143.99,
    'l': 138.8,
    'n': 813347,
    'o': 141.2451,
    't': '2022-05-12T16:00:00Z',
    'v': 94458453,
    'vw': 141.074069})
Bar({   'S': 'AAPL',
    'c': 145.55,
    'h': 145.71,
    'l': 144.5,
    'n': 12406,
    'o': 144.5,
    't': '2022-05-13T02:00:00Z',
    'v': 603758,
    'vw': 145.084316})
Bar({   'S': 'AAPL',
    'c': 147.2089,
    'h': 148.105,
    'l': 142.916,
    'n': 897490,
    'o': 145.48,
    't': '2022-05-13T12:00:00Z',
    'v': 112487056,
    'vw': 146.334574})
Bar({   'S': 'AAPL',
    'c': 147.28,
    'h': 147.3,
    'l': 147,
    'n': 2547,
    'o': 147.2,
    't': '2022-05-13T22:00:00Z',
    'v': 211715,
    'vw': 147.197527})
Bar({   'S': 'AAPL',
    'c': 145.7,
    'h': 146.68,
    'l': 145.66,
    'n': 2070,
    'o': 146.68,
    't': '2022-05-16T00:00:00Z',
    'v': 70069,
    'vw': 146.095816})
Bar({   'S': 'AAPL',
    'c': 146.7093,
    'h': 147.39,
    'l': 144.18,
    'n': 503109,
    'o': 145.82,
    't': '2022-05-16T10:00:00Z',
    'v': 55030335,
    'vw': 145.633101})
Bar({   'S': 'TSLA',
    'c': 891.86,
    'h': 934.3999,
    'l': 884.46,
    'n': 651589,
    'o': 899,
    't': '2022-04-29T08:00:00Z',
    'v': 20826462,
    'vw': 910.364386})
Bar({   'S': 'TSLA',
    'c': 877.5,
    'h': 892.81,
    'l': 868,
    'n': 222398,
    'o': 891.88,
    't': '2022-04-29T18:00:00Z',
    'v': 8468767,
    'vw': 878.750304})
Bar({   'S': 'TSLA',
    'c': 877.53,
    'h': 895,
    'l': 844,
    'n': 423011,
    'o': 888.47,
    't': '2022-05-02T06:00:00Z',
    'v': 12666968,
    'vw': 873.18141})
Bar({   'S': 'TSLA',
    'c': 907,
    'h': 909.7499,
    'l': 858.51,
    'n': 349795,
    'o': 877.6567,
    't': '2022-05-02T16:00:00Z',
    'v': 12403769,
    'vw': 880.765867})
Bar({   'S': 'TSLA',
    'c': 903.6,
    'h': 907.67,
    'l': 898.33,
    'n': 4742,
    'o': 903.02,
    't': '2022-05-03T02:00:00Z',
    'v': 93399,
    'vw': 901.740544})
Bar({   'S': 'TSLA',
    'c': 908.5,
    'h': 924.08,
    'l': 888.59,
    'n': 589257,
    'o': 903.75,
    't': '2022-05-03T12:00:00Z',
    'v': 20851089,
    'vw': 908.732212})
Bar({   'S': 'TSLA',
    'c': 907,
    'h': 908.9,
    'l': 906.6,
    'n': 1846,
    'o': 908.5,
    't': '2022-05-03T22:00:00Z',
    'v': 42035,
    'vw': 906.950729})
Bar({   'S': 'TSLA',
    'c': 918.04,
    'h': 920.67,
    'l': 885.28,
    'n': 386271,
    'o': 907,
    't': '2022-05-04T08:00:00Z',
    'v': 12870875,
    'vw': 902.260269})
Bar({   'S': 'TSLA',
    'c': 948.06,
    'h': 955.5,
    'l': 893.24,
    'n': 329408,
    'o': 917.48,
    't': '2022-05-04T18:00:00Z',
    'v': 14162358,
    'vw': 930.728739})
Bar({   'S': 'TSLA',
    'c': 923.94,
    'h': 950.73,
    'l': 919.52,
    'n': 137019,
    'o': 942.9,
    't': '2022-05-05T04:00:00Z',
    'v': 4063211,
    'vw': 932.986521})
Bar({   'S': 'TSLA',
    'c': 878,
    'h': 924.115,
    'l': 857.7,
    'n': 866122,
    'o': 924.115,
    't': '2022-05-05T14:00:00Z',
    'v': 26532186,
    'vw': 883.637065})
Bar({   'S': 'TSLA',
    'c': 878,
    'h': 883,
    'l': 868.5,
    'n': 2421,
    'o': 875.9,
    't': '2022-05-06T00:00:00Z',
    'v': 29661,
    'vw': 873.389837})
Bar({   'S': 'TSLA',
    'c': 865.67,
    'h': 889.88,
    'l': 843.105,
    'n': 762985,
    'o': 876.5,
    't': '2022-05-06T10:00:00Z',
    'v': 23415160,
    'vw': 868.115921})
Bar({   'S': 'TSLA',
    'c': 864,
    'h': 865.79,
    'l': 863,
    'n': 7253,
    'o': 865.79,
    't': '2022-05-06T20:00:00Z',
    'v': 647095,
    'vw': 865.414296})
Bar({   'S': 'TSLA',
    'c': 804.4453,
    'h': 853.24,
    'l': 797.34,
    'n': 790671,
    'o': 853.24,
    't': '2022-05-09T08:00:00Z',
    'v': 20692486,
    'vw': 817.139835})
Bar({   'S': 'TSLA',
    'c': 786.7,
    'h': 807.32,
    'l': 781.15,
    'n': 323065,
    'o': 804.22,
    't': '2022-05-09T18:00:00Z',
    'v': 9324200,
    'vw': 794.204281})
Bar({   'S': 'TSLA',
    'c': 809.675,
    'h': 825.36,
    'l': 794.1152,
    'n': 207403,
    'o': 808,
    't': '2022-05-10T04:00:00Z',
    'v': 5645251,
    'vw': 808.878087})
Bar({   'S': 'TSLA',
    'c': 797.75,
    'h': 823.79,
    'l': 774.25,
    'n': 671013,
    'o': 809.545,
    't': '2022-05-10T14:00:00Z',
    'v': 22259629,
    'vw': 798.23521})
Bar({   'S': 'TSLA',
    'c': 813.5,
    'h': 816,
    'l': 808,
    'n': 3611,
    'o': 813.04,
    't': '2022-05-11T00:00:00Z',
    'v': 63941,
    'vw': 812.569737})
Bar({   'S': 'TSLA',
    'c': 734.34,
    'h': 818,
    'l': 727.2,
    'n': 1089167,
    'o': 814,
    't': '2022-05-11T10:00:00Z',
    'v': 30666210,
    'vw': 767.185694})
Bar({   'S': 'TSLA',
    'c': 734.1,
    'h': 744,
    'l': 731.21,
    'n': 33678,
    'o': 734.42,
    't': '2022-05-11T20:00:00Z',
    'v': 1425752,
    'vw': 734.806407})
Bar({   'S': 'TSLA',
    'c': 722.9636,
    'h': 759.66,
    'l': 680,
    'n': 906749,
    'o': 731.59,
    't': '2022-05-12T06:00:00Z',
    'v': 28879200,
    'vw': 720.826201})
Bar({   'S': 'TSLA',
    'c': 741,
    'h': 742.75,
    'l': 705.5,
    'n': 469271,
    'o': 722.875,
    't': '2022-05-12T16:00:00Z',
    'v': 17638588,
    'vw': 721.186647})
Bar({   'S': 'TSLA',
    'c': 772,
    'h': 781.98,
    'l': 749,
    'n': 34035,
    'o': 749,
    't': '2022-05-13T02:00:00Z',
    'v': 850816,
    'vw': 769.060041})
Bar({   'S': 'TSLA',
    'c': 772.2,
    'h': 787.3499,
    'l': 751.565,
    'n': 814000,
    'o': 766.01,
    't': '2022-05-13T12:00:00Z',
    'v': 29576408,
    'vw': 769.741312})
Bar({   'S': 'TSLA',
    'c': 775.7,
    'h': 775.7,
    'l': 772,
    'n': 2785,
    'o': 772.2,
    't': '2022-05-13T22:00:00Z',
    'v': 62267,
    'vw': 773.92012})
Bar({   'S': 'TSLA',
    'c': 767.03,
    'h': 773.42,
    'l': 757.43,
    'n': 3624,
    'o': 765,
    't': '2022-05-16T00:00:00Z',
    'v': 65857,
    'vw': 764.800389})
Bar({   'S': 'TSLA',
    'c': 733.5,
    'h': 774.27,
    'l': 719.0885,
    'n': 635048,
    'o': 767.72,
    't': '2022-05-16T10:00:00Z',
    'v': 21335767,
    'vw': 744.050475})

### Getting Quotes
Quotes are the biddings that has been done.

In [ ]:
df = api.get_quotes(symbols, start="2022-04-29",limit=1000).df.reset_index()
df

,timestamp,ask_exchange,ask_price,ask_size,bid_exchange,bid_price,bid_size,conditions,tape,symbol
0,2022-04-29 08:00:00.001169445+00:00,,0.00,0,Q,160.66,4,[Y],C,AAPL
1,2022-04-29 08:00:00.001241377+00:00,Q,160.93,4,Q,160.66,4,[R],C,AAPL
2,2022-04-29 08:00:00.005655+00:00,Q,160.93,4,K,161.50,1,[R],C,AAPL
3,2022-04-29 08:00:00.005655+00:00,Q,160.93,4,Q,160.66,4,[R],C,AAPL
4,2022-04-29 08:00:00.005655+00:00,Q,160.93,4,K,161.00,1,[R],C,AAPL
...,...,...,...,...,...,...,...,...,...,...
995,2022-04-29 08:22:05.119679488+00:00,P,160.55,2,Q,160.52,1,[R],C,AAPL
996,2022-04-29 08:22:05.119927355+00:00,Q,160.59,6,Q,160.55,1,[R],C,AAPL
997,2022-04-29 08:22:05.119937180+00:00,Q,160.59,6,P,160.52,1,[R],C,AAPL
998,2022-04-29 08:22:05.120335360+00:00,P,160.55,1,Q,160.52,1,[R],C,AAPL
999,2022-04-29 08:22:05.120487168+00:00,P,160.55,3,Q,160.52,1,[R],C,AAPL

There are various fileds and there is a well described documentation in [docs](https://alpaca.markets/deprecated/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/historical/).

### Getting Trade
To view the trades that has actually happened.

In [ ]:
df = api.get_trades(symbols, start="2022-04-29",limit=1000).df.reset_index()
df

,timestamp,exchange,price,size,conditions,id,tape,symbol
0,2022-04-29 04:00:13.553000+00:00,D,160.09,1,"[@, T, I]",927,C,AAPL
1,2022-04-29 04:00:43.779000+00:00,D,160.09,220,"[@, T]",871,C,AAPL
2,2022-04-29 04:02:52.730000+00:00,D,160.10,1,"[@, T, I]",912,C,AAPL
3,2022-04-29 04:02:52.730000+00:00,D,160.10,4,"[@, T, I]",940,C,AAPL
4,2022-04-29 04:06:04.276000+00:00,D,160.10,20,"[@, T, I]",941,C,AAPL
...,...,...,...,...,...,...,...,...
995,2022-04-29 08:09:30.317838547+00:00,Q,160.63,1,"[@, F, T, I]",430,C,AAPL
996,2022-04-29 08:09:30.617365760+00:00,P,160.61,137,"[@, F, T]",258,C,AAPL
997,2022-04-29 08:09:30.617365760+00:00,P,160.60,74,"[@, F, T, I]",259,C,AAPL
998,2022-04-29 08:09:30.756697344+00:00,P,160.60,2,"[@, T, I]",260,C,AAPL
999,2022-04-29 08:09:32.422441+00:00,K,160.60,10,"[@, F, T, I]",129,C,AAPL

Alpaca provides other Rest APIs too which can be seen in their module https://github.com/alpacahq/alpaca-trade-api-python/blob/master/alpaca_trade_api/rest.py. Most of the REST APIs have iterable functions too like `get_bars_iter`, `get_quote_iter`.

## Streaming Data
Streaming Data is done to get realtime data and Alpaca provides websockets to do that. To do so, we will use `async` keyword in front of the function that will be awaitable. Below code is taken from the GitHub repo of [Alpaca package](https://github.com/alpacahq/alpaca-trade-api-python).

In [ ]:
from alpaca_trade_api.stream import Stream
from alpaca_trade_api.common import URL

async def trade_callback(t):
    print('trade', t)


async def quote_callback(q):
    print('quote', q)


# Initiate Class Instance
stream = Stream(key,
                secret,
                base_url=URL('https://paper-api.alpaca.markets'),
                data_feed='iex') 

# subscribing to event
stream.subscribe_trades(trade_callback, 'AAPL')
stream.subscribe_quotes(quote_callback, 'IBM')

stream.run()

RuntimeError: ignored

There are some other streamming APIs also like `subscribe_bars` which can be seen inside a module [stream.py](https://github.com/alpacahq/alpaca-trade-api-python/blob/master/alpaca_trade_api/stream.py).

### How to stream bars data?
By default there is not a possibility to stream a bars data but one can do it by using `asyncio` in Python.

This section will be updated soon. Sorry.